export default {
  remembered: {
    Default: {
      0: {
        cubedimX: 15,
        cubedimY: 15,
        cubedimZ: 15,
        depthDim: 2,
        mag: 5,
        tx: 0,
        ty: 0,
        shadeOpacityFront: 0.2,
        shadeOpacityLeft: 0.1,
        shadeOpacityTop: 0,
        outerStrokeWeight: 2,
        innerStrokeWeight: 1,
        outerSize: 0.97,
        minGridSize: 5,
        innerSize: 0.8,
        perspective: 0.85,
        colorMode: 'group',
        palette: 'tsu_arcade',
        paletteShift: 0,
      },
    },
    archetypish: {
      0: {
        cubedimX: 35,
        cubedimY: 5,
        cubedimZ: 35,
        depthDim: 2,
        mag: 12,
        tx: 0,
        ty: 800,
        shadeOpacityFront: 1,
        shadeOpacityLeft: 1,
        shadeOpacityTop: 0,
        outerStrokeWeight: 3,
        innerStrokeWeight: 1,
        outerSize: 0.97,
        minGridSize: 5,
        innerSize: 0.8,
        perspective: 1,
        colorMode: 'group',
        palette: 'tsu_arcade',
        paletteShift: 0,
      },
    },
  },
  closed: false,
};
